# Replace 'group_project_db' with the name you chose in Part 2
spring.datasource.url=jdbc:postgresql://localhost:5433/ph-gdae-project
  
# Default username is usually 'postgres'
spring.datasource.username=postgres
  
# REPLACE THIS with the password you created in Part 1
spring.datasource.password=leverage4192608##

spring.data.rest.base-path=/api
spring.data.rest.detection-strategy=annotated


spring.security.oauth2.client.registration.google.client-id=873429492204-457jhqhsvph8m590a3v5fq1ai87erssn.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE

# --- HIBERNATE SETTINGS (Magic that creates tables for you) ---
# Automatically updates the database schema when you change Java code
spring.jpa.hibernate.ddl-auto=update
  
  # Shows the SQL commands in the console (helpful for debugging)
spring.jpa.show-sql=true
  
  # Tells Hibernate we are using PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

